name: Node.js - Yarn

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Update api url and set version
        run: |
          today=`date '+%y%m%d'`
          stage=`echo ${GITHUB_SHA} | cut -b 1-7`
          sed -i "s#yourapiaddress#${{ secrets.API }}#g" src/global.ts
          sed -i "s#YOURDATEVER#$today#g" src/global.ts
          sed -i "s#YOURCOMMITVER#$stage#g" src/global.ts

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-mui-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-mui-

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build"
          target: "/tmp"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            /bin/bash /usr/mycrond/update_web.sh
